#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

yarn run format:staged && yarn run lint:staged ||
(
    echo '🤢🤮🤢🤮 Its RAW - Your styling looks disgusting. 🤢🤮🤢🤮
            Prettier Check Failed. Run yarn run lint:fix, add changes and try commit again.';
    false;
)

echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'