#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn run test && yarn run build ||
(
    echo '❌👷🔨❌ Better call Bob... Because your need help to resolve the tests ❌👷🔨❌';
    false;
)

echo '✅✅✅ You win this time... I am pushing this now. ✅✅✅✅'